name: 'CodeCritique - Setup Tool'
description: 'Common setup steps for CodeCritique actions: checkout, resolve tool root, setup Node.js, install dependencies, and download artifacts'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true

outputs:
  tool-root:
    description: 'Root directory of the CodeCritique tool'
    value: ${{ steps.tool.outputs.tool-root }}

  embeddings-available:
    description: 'Whether embeddings artifacts were successfully downloaded'
    value: ${{ steps.setup-artifacts.outcome == 'success' }}

runs:
  using: 'composite'
  steps:
    - name: Set Tool Root from Action Repository
      id: tool
      shell: bash
      run: |
        # Use the action repository that GitHub Actions already checked out
        # The .action-repo symlink points to the correct CodeCritique repository
        if [ -L "$GITHUB_WORKSPACE/.action-repo" ]; then
          TOOL_ROOT="$(readlink -f "$GITHUB_WORKSPACE/.action-repo")"
          echo "tool-root=$TOOL_ROOT" >> $GITHUB_OUTPUT
          echo "✅ Using tool from symlinked action repo: $TOOL_ROOT"
        else
          echo "❌ .action-repo symlink not found"
          exit 1
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: '.action-repo/package-lock.json'

    - name: Install AI Tool Dependencies
      shell: bash
      working-directory: ${{ steps.tool.outputs.tool-root }}
      run: |
        echo "📦 Installing CodeCritique tool dependencies..."
        npm ci --no-audit --silent

    - name: Download Embeddings Artifacts
      id: setup-artifacts
      uses: dawidd6/action-download-artifact@v11
      with:
        name: codecritique-embeddings-${{ github.repository_id }}
        # Look specifically in the default branch where embeddings are generated daily
        branch: ${{ github.event.repository.default_branch }}
        # Only look for successful workflow conclusions
        workflow_conclusion: success
        search_artifacts: false
        # Common embeddings workflow names to search for
        workflow: generate-embeddings.yml
        # Warn but don't fail if no artifacts found
        if_no_artifact_found: warn
        # Use provided GitHub token
        github_token: ${{ inputs.github-token }}
      continue-on-error: true

    - name: Setup Embeddings Directories
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Artifact download may extract to current directory or a subdirectory
        ARTIFACT_SUBDIR="codecritique-embeddings-${{ github.repository_id }}"

        echo "📦 Setting up embeddings from artifacts..."

        # Determine where artifacts were extracted
        if [ -f "lancedb.tar.gz" ] || [ -f "fastembed-cache.tar.gz" ]; then
          # New format: tar archives extracted to current directory
          ARTIFACT_PATH="."
        elif [ -d "$ARTIFACT_SUBDIR" ]; then
          # Artifacts in subdirectory
          ARTIFACT_PATH="$ARTIFACT_SUBDIR"
        else
          echo "⚠️  No artifact directory or files found"
          ARTIFACT_PATH=""
        fi

        if [ -n "$ARTIFACT_PATH" ]; then
          # Extract LanceDB tar archive if it exists (new format)
          if [ -f "$ARTIFACT_PATH/lancedb.tar.gz" ]; then
            echo "  Extracting lancedb.tar.gz..."
            tar -xzf "$ARTIFACT_PATH/lancedb.tar.gz" -C "${{ github.workspace }}"
            rm -f "$ARTIFACT_PATH/lancedb.tar.gz"
            echo "  ✅ LanceDB extracted"
          # Fallback: Move directory if it exists (old format)
          elif [ -d "$ARTIFACT_PATH/.ai-review-lancedb" ]; then
            echo "  Moving .ai-review-lancedb directory (legacy format)..."
            mv "$ARTIFACT_PATH/.ai-review-lancedb" "${{ github.workspace }}/.ai-review-lancedb"
          fi

          # Extract FastEmbed cache tar archive if it exists (new format)
          if [ -f "$ARTIFACT_PATH/fastembed-cache.tar.gz" ]; then
            echo "  Extracting fastembed-cache.tar.gz..."
            tar -xzf "$ARTIFACT_PATH/fastembed-cache.tar.gz" -C "${{ github.workspace }}"
            rm -f "$ARTIFACT_PATH/fastembed-cache.tar.gz"
            echo "  ✅ FastEmbed cache extracted"
          # Fallback: Move directory if it exists (old format)
          elif [ -d "$ARTIFACT_PATH/.ai-review-fastembed-cache" ]; then
            echo "  Moving .ai-review-fastembed-cache directory (legacy format)..."
            mv "$ARTIFACT_PATH/.ai-review-fastembed-cache" "${{ github.workspace }}/.ai-review-fastembed-cache"
          fi

          # Clean up artifact subdirectory if it was used
          if [ "$ARTIFACT_PATH" = "$ARTIFACT_SUBDIR" ]; then
            rm -rf "$ARTIFACT_SUBDIR" 2>/dev/null || true
          fi
        fi

        # Report what was set up
        if [ -d "${{ github.workspace }}/.ai-review-lancedb" ]; then
          echo "✅ LanceDB embeddings available"
        else
          echo "⚠️  No LanceDB embeddings found"
        fi

        if [ -d "${{ github.workspace }}/.ai-review-fastembed-cache" ]; then
          echo "✅ FastEmbed cache available"
        else
          echo "⚠️  No FastEmbed cache found"
        fi
